
#https://www.netlifycms.org/docs/add-to-your-site/#configuration

backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

# media uploads from the CMS go here
media_folder: "dev/sources/assets/images/uploads"
public_folder: "/assets/images/uploads"

#blog settings
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "dev/content/blog/{{year}}" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}/{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}